// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/account/account-request.proto

package com.example.common.api.accountRequest;

public final class AccountRequestOuterClass {
  private AccountRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_api_account_AccountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_api_account_AccountRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'proto/api/account/account-request.prot" +
      "o\022\021proto.api.account\032&proto/api/account/" +
      "account-common.proto\"\363\001\n\016AccountRequest\022" +
      "\017\n\007balance\030\002 \001(\005\022\021\n\tfirstname\030\003 \001(\t\022\020\n\010l" +
      "astname\030\004 \001(\t\022\013\n\003age\030\005 \001(\005\022/\n\006gender\030\006 \001" +
      "(\0162\037.proto.api.account.GenderCommon\022\017\n\007a" +
      "ddress\030\007 \001(\t\022\020\n\010employer\030\t \001(\t\022\r\n\005email\030" +
      "\n \001(\t\022\014\n\004city\030\013 \001(\t\022-\n\005state\030\014 \001(\0162\036.pro" +
      "to.api.account.StateCommonB)\n%com.exampl" +
      "e.common.api.accountRequestP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.common.api.accountCommon.AccountCommon.getDescriptor(),
        }, assigner);
    internal_static_proto_api_account_AccountRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_api_account_AccountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_api_account_AccountRequest_descriptor,
        new java.lang.String[] { "Balance", "Firstname", "Lastname", "Age", "Gender", "Address", "Employer", "Email", "City", "State", });
    com.example.common.api.accountCommon.AccountCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
