// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/account/account-request.proto

package com.example.common.api.accountRequest;

public interface AccountRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.api.account.AccountRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 balance = 2;</code>
   */
  int getBalance();

  /**
   * <code>string firstname = 3;</code>
   */
  java.lang.String getFirstname();
  /**
   * <code>string firstname = 3;</code>
   */
  com.google.protobuf.ByteString
      getFirstnameBytes();

  /**
   * <code>string lastname = 4;</code>
   */
  java.lang.String getLastname();
  /**
   * <code>string lastname = 4;</code>
   */
  com.google.protobuf.ByteString
      getLastnameBytes();

  /**
   * <code>int32 age = 5;</code>
   */
  int getAge();

  /**
   * <code>.proto.api.account.GenderCommon gender = 6;</code>
   */
  int getGenderValue();
  /**
   * <code>.proto.api.account.GenderCommon gender = 6;</code>
   */
  com.example.common.api.accountCommon.GenderCommon getGender();

  /**
   * <code>string address = 7;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 7;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string employer = 9;</code>
   */
  java.lang.String getEmployer();
  /**
   * <code>string employer = 9;</code>
   */
  com.google.protobuf.ByteString
      getEmployerBytes();

  /**
   * <code>string email = 10;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 10;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string city = 11;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 11;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>.proto.api.account.StateCommon state = 12;</code>
   */
  int getStateValue();
  /**
   * <code>.proto.api.account.StateCommon state = 12;</code>
   */
  com.example.common.api.accountCommon.StateCommon getState();
}
