// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/account/account-response.proto

package com.example.common.api.accountResponse;

public final class AccountResponseOuterClass {
  private AccountResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_api_account_AccountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_api_account_AccountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(proto/api/account/account-response.pro" +
      "to\022\021proto.api.account\032&proto/api/account" +
      "/account-common.proto\"\213\002\n\017AccountRespons" +
      "e\022\025\n\raccountNumber\030\001 \001(\003\022\017\n\007balance\030\002 \001(" +
      "\005\022\021\n\tfirstname\030\003 \001(\t\022\020\n\010lastname\030\004 \001(\t\022\013" +
      "\n\003age\030\005 \001(\005\022/\n\006gender\030\006 \001(\0162\037.proto.api." +
      "account.GenderCommon\022\017\n\007address\030\007 \001(\t\022\020\n" +
      "\010employer\030\t \001(\t\022\r\n\005email\030\n \001(\t\022\014\n\004city\030\013" +
      " \001(\t\022-\n\005state\030\014 \001(\0162\036.proto.api.account." +
      "StateCommonB*\n&com.example.common.api.ac",
      "countResponseP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.common.api.accountCommon.AccountCommon.getDescriptor(),
        }, assigner);
    internal_static_proto_api_account_AccountResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_api_account_AccountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_api_account_AccountResponse_descriptor,
        new java.lang.String[] { "AccountNumber", "Balance", "Firstname", "Lastname", "Age", "Gender", "Address", "Employer", "Email", "City", "State", });
    com.example.common.api.accountCommon.AccountCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
