logging:
  level: INFO
  loggers:
    com.example.grpcserver: DEBUG

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

grpcServer:
  shutdownDuration: 10 seconds
  port: 8084

elasticsearch:
  hostname: localhost
  port: 9200