// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account-service.proto

package com.example.training.grpc.accountservice;

/**
 * Protobuf type {@code com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse}
 */
public  final class AccountBalanceAverageByStateResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse)
    AccountBalanceAverageByStateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AccountBalanceAverageByStateResponse.newBuilder() to construct.
  private AccountBalanceAverageByStateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AccountBalanceAverageByStateResponse() {
    balanceAverageByStateResponse_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AccountBalanceAverageByStateResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AccountBalanceAverageByStateResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              balanceAverageByStateResponse_ = new java.util.ArrayList<com.example.training.grpc.accountservice.BalanceAverageByStateResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            balanceAverageByStateResponse_.add(
                input.readMessage(com.example.training.grpc.accountservice.BalanceAverageByStateResponse.parser(), extensionRegistry));
            break;
          }
          case 16: {

            docCount_ = input.readInt64();
            break;
          }
          case 24: {

            maxBalance_ = input.readInt64();
            break;
          }
          case 32: {

            minBalance_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        balanceAverageByStateResponse_ = java.util.Collections.unmodifiableList(balanceAverageByStateResponse_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.training.grpc.accountservice.AccountServiceOuterClass.internal_static_com_example_training_grpc_accountservice_AccountBalanceAverageByStateResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.training.grpc.accountservice.AccountServiceOuterClass.internal_static_com_example_training_grpc_accountservice_AccountBalanceAverageByStateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse.class, com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse.Builder.class);
  }

  public static final int BALANCEAVERAGEBYSTATERESPONSE_FIELD_NUMBER = 1;
  private java.util.List<com.example.training.grpc.accountservice.BalanceAverageByStateResponse> balanceAverageByStateResponse_;
  /**
   * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  public java.util.List<com.example.training.grpc.accountservice.BalanceAverageByStateResponse> getBalanceAverageByStateResponseList() {
    return balanceAverageByStateResponse_;
  }
  /**
   * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  public java.util.List<? extends com.example.training.grpc.accountservice.BalanceAverageByStateResponseOrBuilder> 
      getBalanceAverageByStateResponseOrBuilderList() {
    return balanceAverageByStateResponse_;
  }
  /**
   * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  public int getBalanceAverageByStateResponseCount() {
    return balanceAverageByStateResponse_.size();
  }
  /**
   * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  public com.example.training.grpc.accountservice.BalanceAverageByStateResponse getBalanceAverageByStateResponse(int index) {
    return balanceAverageByStateResponse_.get(index);
  }
  /**
   * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  public com.example.training.grpc.accountservice.BalanceAverageByStateResponseOrBuilder getBalanceAverageByStateResponseOrBuilder(
      int index) {
    return balanceAverageByStateResponse_.get(index);
  }

  public static final int DOCCOUNT_FIELD_NUMBER = 2;
  private long docCount_;
  /**
   * <code>int64 docCount = 2;</code>
   */
  public long getDocCount() {
    return docCount_;
  }

  public static final int MAXBALANCE_FIELD_NUMBER = 3;
  private long maxBalance_;
  /**
   * <code>int64 maxBalance = 3;</code>
   */
  public long getMaxBalance() {
    return maxBalance_;
  }

  public static final int MINBALANCE_FIELD_NUMBER = 4;
  private long minBalance_;
  /**
   * <code>int64 minBalance = 4;</code>
   */
  public long getMinBalance() {
    return minBalance_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < balanceAverageByStateResponse_.size(); i++) {
      output.writeMessage(1, balanceAverageByStateResponse_.get(i));
    }
    if (docCount_ != 0L) {
      output.writeInt64(2, docCount_);
    }
    if (maxBalance_ != 0L) {
      output.writeInt64(3, maxBalance_);
    }
    if (minBalance_ != 0L) {
      output.writeInt64(4, minBalance_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < balanceAverageByStateResponse_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, balanceAverageByStateResponse_.get(i));
    }
    if (docCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, docCount_);
    }
    if (maxBalance_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, maxBalance_);
    }
    if (minBalance_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, minBalance_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse)) {
      return super.equals(obj);
    }
    com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse other = (com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse) obj;

    if (!getBalanceAverageByStateResponseList()
        .equals(other.getBalanceAverageByStateResponseList())) return false;
    if (getDocCount()
        != other.getDocCount()) return false;
    if (getMaxBalance()
        != other.getMaxBalance()) return false;
    if (getMinBalance()
        != other.getMinBalance()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBalanceAverageByStateResponseCount() > 0) {
      hash = (37 * hash) + BALANCEAVERAGEBYSTATERESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getBalanceAverageByStateResponseList().hashCode();
    }
    hash = (37 * hash) + DOCCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDocCount());
    hash = (37 * hash) + MAXBALANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMaxBalance());
    hash = (37 * hash) + MINBALANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMinBalance());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse)
      com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.training.grpc.accountservice.AccountServiceOuterClass.internal_static_com_example_training_grpc_accountservice_AccountBalanceAverageByStateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.training.grpc.accountservice.AccountServiceOuterClass.internal_static_com_example_training_grpc_accountservice_AccountBalanceAverageByStateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse.class, com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse.Builder.class);
    }

    // Construct using com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBalanceAverageByStateResponseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (balanceAverageByStateResponseBuilder_ == null) {
        balanceAverageByStateResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        balanceAverageByStateResponseBuilder_.clear();
      }
      docCount_ = 0L;

      maxBalance_ = 0L;

      minBalance_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.training.grpc.accountservice.AccountServiceOuterClass.internal_static_com_example_training_grpc_accountservice_AccountBalanceAverageByStateResponse_descriptor;
    }

    @java.lang.Override
    public com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse getDefaultInstanceForType() {
      return com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse build() {
      com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse buildPartial() {
      com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse result = new com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse(this);
      int from_bitField0_ = bitField0_;
      if (balanceAverageByStateResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          balanceAverageByStateResponse_ = java.util.Collections.unmodifiableList(balanceAverageByStateResponse_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.balanceAverageByStateResponse_ = balanceAverageByStateResponse_;
      } else {
        result.balanceAverageByStateResponse_ = balanceAverageByStateResponseBuilder_.build();
      }
      result.docCount_ = docCount_;
      result.maxBalance_ = maxBalance_;
      result.minBalance_ = minBalance_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse) {
        return mergeFrom((com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse other) {
      if (other == com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse.getDefaultInstance()) return this;
      if (balanceAverageByStateResponseBuilder_ == null) {
        if (!other.balanceAverageByStateResponse_.isEmpty()) {
          if (balanceAverageByStateResponse_.isEmpty()) {
            balanceAverageByStateResponse_ = other.balanceAverageByStateResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBalanceAverageByStateResponseIsMutable();
            balanceAverageByStateResponse_.addAll(other.balanceAverageByStateResponse_);
          }
          onChanged();
        }
      } else {
        if (!other.balanceAverageByStateResponse_.isEmpty()) {
          if (balanceAverageByStateResponseBuilder_.isEmpty()) {
            balanceAverageByStateResponseBuilder_.dispose();
            balanceAverageByStateResponseBuilder_ = null;
            balanceAverageByStateResponse_ = other.balanceAverageByStateResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
            balanceAverageByStateResponseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBalanceAverageByStateResponseFieldBuilder() : null;
          } else {
            balanceAverageByStateResponseBuilder_.addAllMessages(other.balanceAverageByStateResponse_);
          }
        }
      }
      if (other.getDocCount() != 0L) {
        setDocCount(other.getDocCount());
      }
      if (other.getMaxBalance() != 0L) {
        setMaxBalance(other.getMaxBalance());
      }
      if (other.getMinBalance() != 0L) {
        setMinBalance(other.getMinBalance());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.training.grpc.accountservice.BalanceAverageByStateResponse> balanceAverageByStateResponse_ =
      java.util.Collections.emptyList();
    private void ensureBalanceAverageByStateResponseIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        balanceAverageByStateResponse_ = new java.util.ArrayList<com.example.training.grpc.accountservice.BalanceAverageByStateResponse>(balanceAverageByStateResponse_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.training.grpc.accountservice.BalanceAverageByStateResponse, com.example.training.grpc.accountservice.BalanceAverageByStateResponse.Builder, com.example.training.grpc.accountservice.BalanceAverageByStateResponseOrBuilder> balanceAverageByStateResponseBuilder_;

    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public java.util.List<com.example.training.grpc.accountservice.BalanceAverageByStateResponse> getBalanceAverageByStateResponseList() {
      if (balanceAverageByStateResponseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(balanceAverageByStateResponse_);
      } else {
        return balanceAverageByStateResponseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public int getBalanceAverageByStateResponseCount() {
      if (balanceAverageByStateResponseBuilder_ == null) {
        return balanceAverageByStateResponse_.size();
      } else {
        return balanceAverageByStateResponseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public com.example.training.grpc.accountservice.BalanceAverageByStateResponse getBalanceAverageByStateResponse(int index) {
      if (balanceAverageByStateResponseBuilder_ == null) {
        return balanceAverageByStateResponse_.get(index);
      } else {
        return balanceAverageByStateResponseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public Builder setBalanceAverageByStateResponse(
        int index, com.example.training.grpc.accountservice.BalanceAverageByStateResponse value) {
      if (balanceAverageByStateResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBalanceAverageByStateResponseIsMutable();
        balanceAverageByStateResponse_.set(index, value);
        onChanged();
      } else {
        balanceAverageByStateResponseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public Builder setBalanceAverageByStateResponse(
        int index, com.example.training.grpc.accountservice.BalanceAverageByStateResponse.Builder builderForValue) {
      if (balanceAverageByStateResponseBuilder_ == null) {
        ensureBalanceAverageByStateResponseIsMutable();
        balanceAverageByStateResponse_.set(index, builderForValue.build());
        onChanged();
      } else {
        balanceAverageByStateResponseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public Builder addBalanceAverageByStateResponse(com.example.training.grpc.accountservice.BalanceAverageByStateResponse value) {
      if (balanceAverageByStateResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBalanceAverageByStateResponseIsMutable();
        balanceAverageByStateResponse_.add(value);
        onChanged();
      } else {
        balanceAverageByStateResponseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public Builder addBalanceAverageByStateResponse(
        int index, com.example.training.grpc.accountservice.BalanceAverageByStateResponse value) {
      if (balanceAverageByStateResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBalanceAverageByStateResponseIsMutable();
        balanceAverageByStateResponse_.add(index, value);
        onChanged();
      } else {
        balanceAverageByStateResponseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public Builder addBalanceAverageByStateResponse(
        com.example.training.grpc.accountservice.BalanceAverageByStateResponse.Builder builderForValue) {
      if (balanceAverageByStateResponseBuilder_ == null) {
        ensureBalanceAverageByStateResponseIsMutable();
        balanceAverageByStateResponse_.add(builderForValue.build());
        onChanged();
      } else {
        balanceAverageByStateResponseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public Builder addBalanceAverageByStateResponse(
        int index, com.example.training.grpc.accountservice.BalanceAverageByStateResponse.Builder builderForValue) {
      if (balanceAverageByStateResponseBuilder_ == null) {
        ensureBalanceAverageByStateResponseIsMutable();
        balanceAverageByStateResponse_.add(index, builderForValue.build());
        onChanged();
      } else {
        balanceAverageByStateResponseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public Builder addAllBalanceAverageByStateResponse(
        java.lang.Iterable<? extends com.example.training.grpc.accountservice.BalanceAverageByStateResponse> values) {
      if (balanceAverageByStateResponseBuilder_ == null) {
        ensureBalanceAverageByStateResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, balanceAverageByStateResponse_);
        onChanged();
      } else {
        balanceAverageByStateResponseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public Builder clearBalanceAverageByStateResponse() {
      if (balanceAverageByStateResponseBuilder_ == null) {
        balanceAverageByStateResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        balanceAverageByStateResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public Builder removeBalanceAverageByStateResponse(int index) {
      if (balanceAverageByStateResponseBuilder_ == null) {
        ensureBalanceAverageByStateResponseIsMutable();
        balanceAverageByStateResponse_.remove(index);
        onChanged();
      } else {
        balanceAverageByStateResponseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public com.example.training.grpc.accountservice.BalanceAverageByStateResponse.Builder getBalanceAverageByStateResponseBuilder(
        int index) {
      return getBalanceAverageByStateResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public com.example.training.grpc.accountservice.BalanceAverageByStateResponseOrBuilder getBalanceAverageByStateResponseOrBuilder(
        int index) {
      if (balanceAverageByStateResponseBuilder_ == null) {
        return balanceAverageByStateResponse_.get(index);  } else {
        return balanceAverageByStateResponseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public java.util.List<? extends com.example.training.grpc.accountservice.BalanceAverageByStateResponseOrBuilder> 
         getBalanceAverageByStateResponseOrBuilderList() {
      if (balanceAverageByStateResponseBuilder_ != null) {
        return balanceAverageByStateResponseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(balanceAverageByStateResponse_);
      }
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public com.example.training.grpc.accountservice.BalanceAverageByStateResponse.Builder addBalanceAverageByStateResponseBuilder() {
      return getBalanceAverageByStateResponseFieldBuilder().addBuilder(
          com.example.training.grpc.accountservice.BalanceAverageByStateResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public com.example.training.grpc.accountservice.BalanceAverageByStateResponse.Builder addBalanceAverageByStateResponseBuilder(
        int index) {
      return getBalanceAverageByStateResponseFieldBuilder().addBuilder(
          index, com.example.training.grpc.accountservice.BalanceAverageByStateResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
     */
    public java.util.List<com.example.training.grpc.accountservice.BalanceAverageByStateResponse.Builder> 
         getBalanceAverageByStateResponseBuilderList() {
      return getBalanceAverageByStateResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.training.grpc.accountservice.BalanceAverageByStateResponse, com.example.training.grpc.accountservice.BalanceAverageByStateResponse.Builder, com.example.training.grpc.accountservice.BalanceAverageByStateResponseOrBuilder> 
        getBalanceAverageByStateResponseFieldBuilder() {
      if (balanceAverageByStateResponseBuilder_ == null) {
        balanceAverageByStateResponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.training.grpc.accountservice.BalanceAverageByStateResponse, com.example.training.grpc.accountservice.BalanceAverageByStateResponse.Builder, com.example.training.grpc.accountservice.BalanceAverageByStateResponseOrBuilder>(
                balanceAverageByStateResponse_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        balanceAverageByStateResponse_ = null;
      }
      return balanceAverageByStateResponseBuilder_;
    }

    private long docCount_ ;
    /**
     * <code>int64 docCount = 2;</code>
     */
    public long getDocCount() {
      return docCount_;
    }
    /**
     * <code>int64 docCount = 2;</code>
     */
    public Builder setDocCount(long value) {
      
      docCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 docCount = 2;</code>
     */
    public Builder clearDocCount() {
      
      docCount_ = 0L;
      onChanged();
      return this;
    }

    private long maxBalance_ ;
    /**
     * <code>int64 maxBalance = 3;</code>
     */
    public long getMaxBalance() {
      return maxBalance_;
    }
    /**
     * <code>int64 maxBalance = 3;</code>
     */
    public Builder setMaxBalance(long value) {
      
      maxBalance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 maxBalance = 3;</code>
     */
    public Builder clearMaxBalance() {
      
      maxBalance_ = 0L;
      onChanged();
      return this;
    }

    private long minBalance_ ;
    /**
     * <code>int64 minBalance = 4;</code>
     */
    public long getMinBalance() {
      return minBalance_;
    }
    /**
     * <code>int64 minBalance = 4;</code>
     */
    public Builder setMinBalance(long value) {
      
      minBalance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 minBalance = 4;</code>
     */
    public Builder clearMinBalance() {
      
      minBalance_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse)
  private static final com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse();
  }

  public static com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AccountBalanceAverageByStateResponse>
      PARSER = new com.google.protobuf.AbstractParser<AccountBalanceAverageByStateResponse>() {
    @java.lang.Override
    public AccountBalanceAverageByStateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AccountBalanceAverageByStateResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AccountBalanceAverageByStateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AccountBalanceAverageByStateResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

