// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account-service.proto

package com.example.training.grpc.accountservice;

public interface AccountIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.training.grpc.accountservice.AccountIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Uid = 1;</code>
   */
  java.lang.String getUid();
  /**
   * <code>string Uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();
}
