// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account-service.proto

package com.example.training.grpc.accountservice;

public interface AccountByStateAndAverageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.training.grpc.accountservice.AccountByStateAndAverage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string state = 1;</code>
   */
  java.lang.String getState();
  /**
   * <code>string state = 1;</code>
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>int32 doc_count = 2;</code>
   */
  int getDocCount();

  /**
   * <code>int32 balance_avg = 3;</code>
   */
  int getBalanceAvg();
}
