// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account-service.proto

package com.example.training.grpc.accountservice;

public interface AccountBalanceAverageByStateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.training.grpc.accountservice.AccountBalanceAverageByStateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  java.util.List<com.example.training.grpc.accountservice.BalanceAverageByStateResponse> 
      getBalanceAverageByStateResponseList();
  /**
   * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  com.example.training.grpc.accountservice.BalanceAverageByStateResponse getBalanceAverageByStateResponse(int index);
  /**
   * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  int getBalanceAverageByStateResponseCount();
  /**
   * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  java.util.List<? extends com.example.training.grpc.accountservice.BalanceAverageByStateResponseOrBuilder> 
      getBalanceAverageByStateResponseOrBuilderList();
  /**
   * <code>repeated .com.example.training.grpc.accountservice.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  com.example.training.grpc.accountservice.BalanceAverageByStateResponseOrBuilder getBalanceAverageByStateResponseOrBuilder(
      int index);

  /**
   * <code>int64 docCount = 2;</code>
   */
  long getDocCount();

  /**
   * <code>int64 maxBalance = 3;</code>
   */
  long getMaxBalance();

  /**
   * <code>int64 minBalance = 4;</code>
   */
  long getMinBalance();
}
