// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account-service.proto

package com.example.training.grpc.accountservice;

public final class AccountServiceOuterClass {
  private AccountServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_training_grpc_accountservice_AccountIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_training_grpc_accountservice_AccountIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_training_grpc_accountservice_NewAccount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_training_grpc_accountservice_NewAccount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_training_grpc_accountservice_AccountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_training_grpc_accountservice_AccountResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_training_grpc_accountservice_BalanceAverageByStateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_training_grpc_accountservice_BalanceAverageByStateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_training_grpc_accountservice_AccountBalanceAverageByStateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_training_grpc_accountservice_AccountBalanceAverageByStateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_training_grpc_accountservice_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_training_grpc_accountservice_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025account-service.proto\022(com.example.tra" +
      "ining.grpc.accountservice\"\037\n\020AccountIdRe" +
      "quest\022\013\n\003Uid\030\001 \001(\t\"\221\002\n\nNewAccount\022\017\n\007bal" +
      "ance\030\002 \001(\005\022\021\n\tfirstname\030\003 \001(\t\022\020\n\010lastnam" +
      "e\030\004 \001(\t\022\013\n\003age\030\005 \001(\005\022@\n\006gender\030\006 \001(\01620.c" +
      "om.example.training.grpc.accountservice." +
      "Gender\022\017\n\007address\030\007 \001(\t\022\020\n\010employer\030\t \001(" +
      "\t\022\r\n\005email\030\n \001(\t\022\014\n\004city\030\013 \001(\t\022>\n\005state\030" +
      "\014 \001(\0162/.com.example.training.grpc.accoun" +
      "tservice.State\"\255\002\n\017AccountResponse\022\025\n\rac" +
      "countNumber\030\001 \001(\003\022\017\n\007balance\030\002 \001(\005\022\021\n\tfi" +
      "rstname\030\003 \001(\t\022\020\n\010lastname\030\004 \001(\t\022\013\n\003age\030\005" +
      " \001(\005\022@\n\006gender\030\006 \001(\01620.com.example.train" +
      "ing.grpc.accountservice.Gender\022\017\n\007addres" +
      "s\030\007 \001(\t\022\020\n\010employer\030\t \001(\t\022\r\n\005email\030\n \001(\t" +
      "\022\014\n\004city\030\013 \001(\t\022>\n\005state\030\014 \001(\0162/.com.exam" +
      "ple.training.grpc.accountservice.State\"X" +
      "\n\035BalanceAverageByStateResponse\022\r\n\005state" +
      "\030\001 \001(\t\022\020\n\010docCount\030\002 \001(\003\022\026\n\016balanceAvera" +
      "ge\030\003 \001(\001\"\320\001\n$AccountBalanceAverageByStat" +
      "eResponse\022n\n\035balanceAverageByStateRespon" +
      "se\030\001 \003(\0132G.com.example.training.grpc.acc" +
      "ountservice.BalanceAverageByStateRespons" +
      "e\022\020\n\010docCount\030\002 \001(\003\022\022\n\nmaxBalance\030\003 \001(\003\022" +
      "\022\n\nminBalance\030\004 \001(\003\"\007\n\005Empty*\026\n\006Gender\022\005" +
      "\n\001M\020\000\022\005\n\001F\020\001*\237\001\n\005State\022\006\n\002TX\020\000\022\006\n\002MD\020\001\022\006" +
      "\n\002ID\020\002\022\006\n\002AL\020\003\022\006\n\002ME\020\004\022\006\n\002TN\020\005\022\006\n\002WY\020\006\022\006" +
      "\n\002DC\020\007\022\006\n\002MA\020\010\022\006\n\002ND\020\t\022\006\n\002IL\020\n\022\006\n\002VA\020\013\022\006" +
      "\n\002WA\020\014\022\006\n\002PA\020\r\022\006\n\002IN\020\016\022\006\n\002OK\020\017\022\006\n\002DE\020\020\022\006" +
      "\n\002RI\020\021\022\006\n\002BO\020\0222\250\003\n\016AccountService\022y\n\007fin" +
      "dAll\022/.com.example.training.grpc.account" +
      "service.Empty\0329.com.example.training.grp" +
      "c.accountservice.AccountResponse\"\0000\001\022\235\001\n" +
      "\030findAllByStateAndAverage\022/.com.example." +
      "training.grpc.accountservice.Empty\032N.com" +
      ".example.training.grpc.accountservice.Ac" +
      "countBalanceAverageByStateResponse\"\000\022{\n\006" +
      "create\0224.com.example.training.grpc.accou" +
      "ntservice.NewAccount\0329.com.example.train" +
      "ing.grpc.accountservice.AccountResponse\"" +
      "\000B,\n(com.example.training.grpc.accountse" +
      "rviceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_training_grpc_accountservice_AccountIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_training_grpc_accountservice_AccountIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_training_grpc_accountservice_AccountIdRequest_descriptor,
        new java.lang.String[] { "Uid", });
    internal_static_com_example_training_grpc_accountservice_NewAccount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_training_grpc_accountservice_NewAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_training_grpc_accountservice_NewAccount_descriptor,
        new java.lang.String[] { "Balance", "Firstname", "Lastname", "Age", "Gender", "Address", "Employer", "Email", "City", "State", });
    internal_static_com_example_training_grpc_accountservice_AccountResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_training_grpc_accountservice_AccountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_training_grpc_accountservice_AccountResponse_descriptor,
        new java.lang.String[] { "AccountNumber", "Balance", "Firstname", "Lastname", "Age", "Gender", "Address", "Employer", "Email", "City", "State", });
    internal_static_com_example_training_grpc_accountservice_BalanceAverageByStateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_training_grpc_accountservice_BalanceAverageByStateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_training_grpc_accountservice_BalanceAverageByStateResponse_descriptor,
        new java.lang.String[] { "State", "DocCount", "BalanceAverage", });
    internal_static_com_example_training_grpc_accountservice_AccountBalanceAverageByStateResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_training_grpc_accountservice_AccountBalanceAverageByStateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_training_grpc_accountservice_AccountBalanceAverageByStateResponse_descriptor,
        new java.lang.String[] { "BalanceAverageByStateResponse", "DocCount", "MaxBalance", "MinBalance", });
    internal_static_com_example_training_grpc_accountservice_Empty_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_example_training_grpc_accountservice_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_training_grpc_accountservice_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
