// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account-service.proto

package com.example.training.grpc.accountservice;

public interface BalanceAverageByStateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.training.grpc.accountservice.BalanceAverageByStateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string state = 1;</code>
   */
  java.lang.String getState();
  /**
   * <code>string state = 1;</code>
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>int64 docCount = 2;</code>
   */
  long getDocCount();

  /**
   * <code>double balanceAverage = 3;</code>
   */
  double getBalanceAverage();
}
