// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account-service.proto

package com.example.training.grpc.accountservice;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.training.grpc.accountservice.Empty)
    com.google.protobuf.MessageOrBuilder {
}
