// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/core/account/account-service.proto

package com.example.common.core.account;

public final class AccountServiceOuterClass {
  private AccountServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(proto/core/account/account-service.pro" +
      "to\022\014core.account\032\'proto/api/account/acco" +
      "unt-request.proto\032(proto/api/account/acc" +
      "ount-response.proto\032Zproto/api/account-b" +
      "alance-average-by-state/account-balance-" +
      "average-by-state-response.proto\032\033google/" +
      "protobuf/empty.proto2\263\002\n\016AccountService\022" +
      "I\n\007findAll\022\026.google.protobuf.Empty\032\".pro" +
      "to.api.account.AccountResponse\"\0000\001\022\202\001\n\030f" +
      "indAllByStateAndAverage\022\026.google.protobu",
      "f.Empty\032L.proto.api.accountBalanceAverag" +
      "eByState.AccountBalanceAverageByStateRes" +
      "ponse\"\000\022Q\n\006create\022!.proto.api.account.Ac" +
      "countRequest\032\".proto.api.account.Account" +
      "Response\"\000B#\n\037com.example.common.core.ac" +
      "countP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.common.api.accountRequest.AccountRequestOuterClass.getDescriptor(),
          com.example.common.api.accountResponse.AccountResponseOuterClass.getDescriptor(),
          com.example.common.api.accountBalanceAverageByStateResponse.AccountBalanceAverageByStateResponseOuterClass.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    com.example.common.api.accountRequest.AccountRequestOuterClass.getDescriptor();
    com.example.common.api.accountResponse.AccountResponseOuterClass.getDescriptor();
    com.example.common.api.accountBalanceAverageByStateResponse.AccountBalanceAverageByStateResponseOuterClass.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
