// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/account-balance-average-by-state/account-balance-average-by-state-response.proto

package com.example.common.api.accountBalanceAverageByStateResponse;

public final class AccountBalanceAverageByStateResponseOuterClass {
  private AccountBalanceAverageByStateResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_api_accountBalanceAverageByState_BalanceAverageByStateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_api_accountBalanceAverageByState_BalanceAverageByStateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_api_accountBalanceAverageByState_AccountBalanceAverageByStateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_api_accountBalanceAverageByState_AccountBalanceAverageByStateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nZproto/api/account-balance-average-by-s" +
      "tate/account-balance-average-by-state-re" +
      "sponse.proto\022&proto.api.accountBalanceAv" +
      "erageByState\"X\n\035BalanceAverageByStateRes" +
      "ponse\022\r\n\005state\030\001 \001(\t\022\020\n\010docCount\030\002 \001(\003\022\026" +
      "\n\016balanceAverage\030\003 \001(\001\"\316\001\n$AccountBalanc" +
      "eAverageByStateResponse\022l\n\035balanceAverag" +
      "eByStateResponse\030\001 \003(\0132E.proto.api.accou" +
      "ntBalanceAverageByState.BalanceAverageBy" +
      "StateResponse\022\020\n\010docCount\030\002 \001(\003\022\022\n\nmaxBa",
      "lance\030\003 \001(\003\022\022\n\nminBalance\030\004 \001(\003B?\n;com.e" +
      "xample.common.api.accountBalanceAverageB" +
      "yStateResponseP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_api_accountBalanceAverageByState_BalanceAverageByStateResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_api_accountBalanceAverageByState_BalanceAverageByStateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_api_accountBalanceAverageByState_BalanceAverageByStateResponse_descriptor,
        new java.lang.String[] { "State", "DocCount", "BalanceAverage", });
    internal_static_proto_api_accountBalanceAverageByState_AccountBalanceAverageByStateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_api_accountBalanceAverageByState_AccountBalanceAverageByStateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_api_accountBalanceAverageByState_AccountBalanceAverageByStateResponse_descriptor,
        new java.lang.String[] { "BalanceAverageByStateResponse", "DocCount", "MaxBalance", "MinBalance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
