// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/account-balance-average-by-state/account-balance-average-by-state-response.proto

package com.example.common.api.accountBalanceAverageByStateResponse;

public interface AccountBalanceAverageByStateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.api.accountBalanceAverageByState.AccountBalanceAverageByStateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.api.accountBalanceAverageByState.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  java.util.List<com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse> 
      getBalanceAverageByStateResponseList();
  /**
   * <code>repeated .proto.api.accountBalanceAverageByState.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse getBalanceAverageByStateResponse(int index);
  /**
   * <code>repeated .proto.api.accountBalanceAverageByState.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  int getBalanceAverageByStateResponseCount();
  /**
   * <code>repeated .proto.api.accountBalanceAverageByState.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  java.util.List<? extends com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponseOrBuilder> 
      getBalanceAverageByStateResponseOrBuilderList();
  /**
   * <code>repeated .proto.api.accountBalanceAverageByState.BalanceAverageByStateResponse balanceAverageByStateResponse = 1;</code>
   */
  com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponseOrBuilder getBalanceAverageByStateResponseOrBuilder(
      int index);

  /**
   * <code>int64 docCount = 2;</code>
   */
  long getDocCount();

  /**
   * <code>int64 maxBalance = 3;</code>
   */
  long getMaxBalance();

  /**
   * <code>int64 minBalance = 4;</code>
   */
  long getMinBalance();
}
