// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/account-balance-average-by-state/account-balance-average-by-state-response.proto

package com.example.common.api.accountBalanceAverageByStateResponse;

public interface BalanceAverageByStateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.api.accountBalanceAverageByState.BalanceAverageByStateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string state = 1;</code>
   */
  java.lang.String getState();
  /**
   * <code>string state = 1;</code>
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>int64 docCount = 2;</code>
   */
  long getDocCount();

  /**
   * <code>double balanceAverage = 3;</code>
   */
  double getBalanceAverage();
}
