// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/account-balance-average-by-state/account-balance-average-by-state-response.proto

package com.example.common.api.accountBalanceAverageByStateResponse;

/**
 * Protobuf type {@code proto.api.accountBalanceAverageByState.BalanceAverageByStateResponse}
 */
public  final class BalanceAverageByStateResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.api.accountBalanceAverageByState.BalanceAverageByStateResponse)
    BalanceAverageByStateResponseOrBuilder {
  // Use BalanceAverageByStateResponse.newBuilder() to construct.
  private BalanceAverageByStateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BalanceAverageByStateResponse() {
    state_ = "";
    docCount_ = 0L;
    balanceAverage_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private BalanceAverageByStateResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            state_ = s;
            break;
          }
          case 16: {

            docCount_ = input.readInt64();
            break;
          }
          case 25: {

            balanceAverage_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.common.api.accountBalanceAverageByStateResponse.AccountBalanceAverageByStateResponseOuterClass.internal_static_proto_api_accountBalanceAverageByState_BalanceAverageByStateResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.common.api.accountBalanceAverageByStateResponse.AccountBalanceAverageByStateResponseOuterClass.internal_static_proto_api_accountBalanceAverageByState_BalanceAverageByStateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse.class, com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse.Builder.class);
  }

  public static final int STATE_FIELD_NUMBER = 1;
  private volatile java.lang.Object state_;
  /**
   * <code>string state = 1;</code>
   */
  public java.lang.String getState() {
    java.lang.Object ref = state_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      state_ = s;
      return s;
    }
  }
  /**
   * <code>string state = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStateBytes() {
    java.lang.Object ref = state_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      state_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOCCOUNT_FIELD_NUMBER = 2;
  private long docCount_;
  /**
   * <code>int64 docCount = 2;</code>
   */
  public long getDocCount() {
    return docCount_;
  }

  public static final int BALANCEAVERAGE_FIELD_NUMBER = 3;
  private double balanceAverage_;
  /**
   * <code>double balanceAverage = 3;</code>
   */
  public double getBalanceAverage() {
    return balanceAverage_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, state_);
    }
    if (docCount_ != 0L) {
      output.writeInt64(2, docCount_);
    }
    if (balanceAverage_ != 0D) {
      output.writeDouble(3, balanceAverage_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, state_);
    }
    if (docCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, docCount_);
    }
    if (balanceAverage_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, balanceAverage_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse)) {
      return super.equals(obj);
    }
    com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse other = (com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse) obj;

    boolean result = true;
    result = result && getState()
        .equals(other.getState());
    result = result && (getDocCount()
        == other.getDocCount());
    result = result && (
        java.lang.Double.doubleToLongBits(getBalanceAverage())
        == java.lang.Double.doubleToLongBits(
            other.getBalanceAverage()));
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + getState().hashCode();
    hash = (37 * hash) + DOCCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDocCount());
    hash = (37 * hash) + BALANCEAVERAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBalanceAverage()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.api.accountBalanceAverageByState.BalanceAverageByStateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.api.accountBalanceAverageByState.BalanceAverageByStateResponse)
      com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.common.api.accountBalanceAverageByStateResponse.AccountBalanceAverageByStateResponseOuterClass.internal_static_proto_api_accountBalanceAverageByState_BalanceAverageByStateResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.common.api.accountBalanceAverageByStateResponse.AccountBalanceAverageByStateResponseOuterClass.internal_static_proto_api_accountBalanceAverageByState_BalanceAverageByStateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse.class, com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse.Builder.class);
    }

    // Construct using com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      state_ = "";

      docCount_ = 0L;

      balanceAverage_ = 0D;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.common.api.accountBalanceAverageByStateResponse.AccountBalanceAverageByStateResponseOuterClass.internal_static_proto_api_accountBalanceAverageByState_BalanceAverageByStateResponse_descriptor;
    }

    public com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse getDefaultInstanceForType() {
      return com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse.getDefaultInstance();
    }

    public com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse build() {
      com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse buildPartial() {
      com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse result = new com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse(this);
      result.state_ = state_;
      result.docCount_ = docCount_;
      result.balanceAverage_ = balanceAverage_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse) {
        return mergeFrom((com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse other) {
      if (other == com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse.getDefaultInstance()) return this;
      if (!other.getState().isEmpty()) {
        state_ = other.state_;
        onChanged();
      }
      if (other.getDocCount() != 0L) {
        setDocCount(other.getDocCount());
      }
      if (other.getBalanceAverage() != 0D) {
        setBalanceAverage(other.getBalanceAverage());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object state_ = "";
    /**
     * <code>string state = 1;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string state = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string state = 1;</code>
     */
    public Builder setState(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      state_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string state = 1;</code>
     */
    public Builder clearState() {
      
      state_ = getDefaultInstance().getState();
      onChanged();
      return this;
    }
    /**
     * <code>string state = 1;</code>
     */
    public Builder setStateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      state_ = value;
      onChanged();
      return this;
    }

    private long docCount_ ;
    /**
     * <code>int64 docCount = 2;</code>
     */
    public long getDocCount() {
      return docCount_;
    }
    /**
     * <code>int64 docCount = 2;</code>
     */
    public Builder setDocCount(long value) {
      
      docCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 docCount = 2;</code>
     */
    public Builder clearDocCount() {
      
      docCount_ = 0L;
      onChanged();
      return this;
    }

    private double balanceAverage_ ;
    /**
     * <code>double balanceAverage = 3;</code>
     */
    public double getBalanceAverage() {
      return balanceAverage_;
    }
    /**
     * <code>double balanceAverage = 3;</code>
     */
    public Builder setBalanceAverage(double value) {
      
      balanceAverage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double balanceAverage = 3;</code>
     */
    public Builder clearBalanceAverage() {
      
      balanceAverage_ = 0D;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:proto.api.accountBalanceAverageByState.BalanceAverageByStateResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.api.accountBalanceAverageByState.BalanceAverageByStateResponse)
  private static final com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse();
  }

  public static com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BalanceAverageByStateResponse>
      PARSER = new com.google.protobuf.AbstractParser<BalanceAverageByStateResponse>() {
    public BalanceAverageByStateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new BalanceAverageByStateResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BalanceAverageByStateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BalanceAverageByStateResponse> getParserForType() {
    return PARSER;
  }

  public com.example.common.api.accountBalanceAverageByStateResponse.BalanceAverageByStateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

