// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/account/account-common.proto

package com.example.common.api.accountCommon;

public final class AccountCommon {
  private AccountCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&proto/api/account/account-common.proto" +
      "\022\021proto.api.account*\034\n\014GenderCommon\022\005\n\001M" +
      "\020\000\022\005\n\001F\020\001*\245\001\n\013StateCommon\022\006\n\002TX\020\000\022\006\n\002MD\020" +
      "\001\022\006\n\002ID\020\002\022\006\n\002AL\020\003\022\006\n\002ME\020\004\022\006\n\002TN\020\005\022\006\n\002WY\020" +
      "\006\022\006\n\002DC\020\007\022\006\n\002MA\020\010\022\006\n\002ND\020\t\022\006\n\002IL\020\n\022\006\n\002VA\020" +
      "\013\022\006\n\002WA\020\014\022\006\n\002PA\020\r\022\006\n\002IN\020\016\022\006\n\002OK\020\017\022\006\n\002DE\020" +
      "\020\022\006\n\002RI\020\021\022\006\n\002BO\020\022B(\n$com.example.common." +
      "api.accountCommonP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
