// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/account/account-common.proto

package com.example.common.api.accountCommon;

/**
 * Protobuf enum {@code proto.api.account.GenderCommon}
 */
public enum GenderCommon
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>M = 0;</code>
   */
  M(0),
  /**
   * <code>F = 1;</code>
   */
  F(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>M = 0;</code>
   */
  public static final int M_VALUE = 0;
  /**
   * <code>F = 1;</code>
   */
  public static final int F_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GenderCommon valueOf(int value) {
    return forNumber(value);
  }

  public static GenderCommon forNumber(int value) {
    switch (value) {
      case 0: return M;
      case 1: return F;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GenderCommon>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GenderCommon> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GenderCommon>() {
          public GenderCommon findValueByNumber(int number) {
            return GenderCommon.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.example.common.api.accountCommon.AccountCommon.getDescriptor().getEnumTypes().get(0);
  }

  private static final GenderCommon[] VALUES = values();

  public static GenderCommon valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private GenderCommon(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:proto.api.account.GenderCommon)
}

