// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/api/account/account-common.proto

package com.example.common.api.accountCommon;

/**
 * Protobuf enum {@code proto.api.account.StateCommon}
 */
public enum StateCommon
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TX = 0;</code>
   */
  TX(0),
  /**
   * <code>MD = 1;</code>
   */
  MD(1),
  /**
   * <code>ID = 2;</code>
   */
  ID(2),
  /**
   * <code>AL = 3;</code>
   */
  AL(3),
  /**
   * <code>ME = 4;</code>
   */
  ME(4),
  /**
   * <code>TN = 5;</code>
   */
  TN(5),
  /**
   * <code>WY = 6;</code>
   */
  WY(6),
  /**
   * <code>DC = 7;</code>
   */
  DC(7),
  /**
   * <code>MA = 8;</code>
   */
  MA(8),
  /**
   * <code>ND = 9;</code>
   */
  ND(9),
  /**
   * <code>IL = 10;</code>
   */
  IL(10),
  /**
   * <code>VA = 11;</code>
   */
  VA(11),
  /**
   * <code>WA = 12;</code>
   */
  WA(12),
  /**
   * <code>PA = 13;</code>
   */
  PA(13),
  /**
   * <code>IN = 14;</code>
   */
  IN(14),
  /**
   * <code>OK = 15;</code>
   */
  OK(15),
  /**
   * <code>DE = 16;</code>
   */
  DE(16),
  /**
   * <code>RI = 17;</code>
   */
  RI(17),
  /**
   * <code>BO = 18;</code>
   */
  BO(18),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TX = 0;</code>
   */
  public static final int TX_VALUE = 0;
  /**
   * <code>MD = 1;</code>
   */
  public static final int MD_VALUE = 1;
  /**
   * <code>ID = 2;</code>
   */
  public static final int ID_VALUE = 2;
  /**
   * <code>AL = 3;</code>
   */
  public static final int AL_VALUE = 3;
  /**
   * <code>ME = 4;</code>
   */
  public static final int ME_VALUE = 4;
  /**
   * <code>TN = 5;</code>
   */
  public static final int TN_VALUE = 5;
  /**
   * <code>WY = 6;</code>
   */
  public static final int WY_VALUE = 6;
  /**
   * <code>DC = 7;</code>
   */
  public static final int DC_VALUE = 7;
  /**
   * <code>MA = 8;</code>
   */
  public static final int MA_VALUE = 8;
  /**
   * <code>ND = 9;</code>
   */
  public static final int ND_VALUE = 9;
  /**
   * <code>IL = 10;</code>
   */
  public static final int IL_VALUE = 10;
  /**
   * <code>VA = 11;</code>
   */
  public static final int VA_VALUE = 11;
  /**
   * <code>WA = 12;</code>
   */
  public static final int WA_VALUE = 12;
  /**
   * <code>PA = 13;</code>
   */
  public static final int PA_VALUE = 13;
  /**
   * <code>IN = 14;</code>
   */
  public static final int IN_VALUE = 14;
  /**
   * <code>OK = 15;</code>
   */
  public static final int OK_VALUE = 15;
  /**
   * <code>DE = 16;</code>
   */
  public static final int DE_VALUE = 16;
  /**
   * <code>RI = 17;</code>
   */
  public static final int RI_VALUE = 17;
  /**
   * <code>BO = 18;</code>
   */
  public static final int BO_VALUE = 18;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static StateCommon valueOf(int value) {
    return forNumber(value);
  }

  public static StateCommon forNumber(int value) {
    switch (value) {
      case 0: return TX;
      case 1: return MD;
      case 2: return ID;
      case 3: return AL;
      case 4: return ME;
      case 5: return TN;
      case 6: return WY;
      case 7: return DC;
      case 8: return MA;
      case 9: return ND;
      case 10: return IL;
      case 11: return VA;
      case 12: return WA;
      case 13: return PA;
      case 14: return IN;
      case 15: return OK;
      case 16: return DE;
      case 17: return RI;
      case 18: return BO;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<StateCommon>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      StateCommon> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<StateCommon>() {
          public StateCommon findValueByNumber(int number) {
            return StateCommon.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.example.common.api.accountCommon.AccountCommon.getDescriptor().getEnumTypes().get(1);
  }

  private static final StateCommon[] VALUES = values();

  public static StateCommon valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private StateCommon(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:proto.api.account.StateCommon)
}

